# Develop override settings

url: http://localhost/apierantonio/apierantonio.github.io/

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded